title = "Quid"
gitRepoUrl = "https://github.com/6531503070/Quid"
gitSourceBranch = "main"
changelog = true

[[classOrder]]
classes = ["Quid"]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
tagline = "A suitable uid for representing entity uniqueness. While providing version-detectability, k-sortability and human-readability"
baseUrl = "/Quid/"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Version-Detectable"
description = "The uid can be represent version of item / entity data schema"

[[home.features]]
title = "K-Sortable"
description = "The uid can be K-sortable as it is time-based."

[[home.features]]
title = "Human-Friendly"
description = "The uid is represent as base64url."

[[home.features]]
title = "Random-Customizable"
description = "The random specification can be customized, by providing a config."

[[footer.links]]
title = "Links"

[[footer.links.items]]
label = "GitHub"
href = "https://github.com/6531503070/Quid"

[[navbar.items]]
href = "https://wally.run/package/6531503070/quid"
label = "Wally"
position = "right"
