[package]
name = "6531503070/token"
description = "A typed roblox module for generate token to represent an uniqueness"
version = "3.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
authors = [ "6531503070" ]
exclude = [ "**" ]
include = [ "src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE.md" ]