[package]
name = "6531503070/Token"
version = "2.0.2"
registry = "https://github.com/UpliftGames/wally-index"
licence = "MIT"
authors = ["6531503070"]
description = "A typed roblox module for generate token to represent an uniqueness"
realm = "shared"
exclude = ["**"]
include = [
    "default.project.json",
    "src",
    "src/**",
    "LICENSE",
    "wally.toml",
]

[dependencies]